channels:
  - conda-forge
  - defaults
dependencies:
  - mkl-service>=2.3.0
  - pip>=22.3.1
  - python=3.9.6
  - numpy=1.21.6
  - scipy=1.7.3
  - pip:
      - pymc3==3.11.5
      - arviz==0.12.1
      - matplotlib>=3.6.0
      - tqdm>=4.56.0
      - starry-process==0.9.8
      - starry==1.2.0